# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-30 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30, unique='true')),
                ('email', models.CharField(max_length=50, unique='true')),
                ('password', models.CharField(max_length=30)),
                ('hackerrank', models.CharField(max_length=30, unique='true')),
                ('codeforces', models.CharField(max_length=30, unique='true')),
                ('about', models.CharField(max_length=200)),
            ],
        ),
    ]
